{% set name = "etelemetry" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sensein/{{ name }}-client/archive/v{{ version }}.tar.gz
  sha256: bfec416552d248ad0f50b90ba5ff015e825ad70e4a87f7a06cc7da6d19152897

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - requests
    - ci-info

test:
  imports:
    - etelemetry

about:
  home: https://github.com/sensein/etelemetry-client
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A lightweight python client to communicate with the etelemetry server
  description: |
    A lightweight python client to communicate with the etelemetry server
    to provide version checks for Python developers.
  dev_url: https://github.com/sensein/etelemetry-client

extra:
  recipe-maintainers:
    - mgxd
    - satra
    - effigies
    - yarikoptic
