{% set name = "etelemetry" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sensein/{{ name }}-client/archive/v{{ version }}.tar.gz
  sha256: 7d139f1083a2e75973dacbe8551c766dc695f913b1184c19fdfcb52b3e236117

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - requests

test:
  imports:
    - etelemetry

about:
  home: https://github.com/sensein/etelemetry-client
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'A lightweight python client to communicate with the etelemetry server'
  description: |
    A lightweight python client to communicate with the etelemetry server
    to provide version checks for Python developers.
  dev_url: https://github.com/sensein/etelemetry-client

extra:
  recipe-maintainers:
    - mgxd
    - satra
    - effigies
    - yarikoptic
