travis:
  secure:
    BINSTAR_TOKEN: sCOrpBgysfr5C0ZNDmtBZLXXL2R3z2tOv21cGz/7zcJw5+aBVYlwiZi9dtwA7aNrsv5vddRojpqATMTChdyj79I4gGMy4U4Os/2MDP8qqakoMMN9i9yScnEDgO8KZEG8FlIPN3pIVLxNz6HSL2uWwp2QZkPw4ldAM/ggqEv/5mJXGKPRfu79+sT8/mmTjXt17GRGXxKYzo7Z1z9BPEnYoa9O5BoqXxVlTeP6MmVVqEuoIoJf3svygdJ3MiknJQ+srYtGg3a/P7QvfQnAp7Ou2fPNePgSOODAUFSx29OmkJVe8c+S2yVZa0VWPk3EFbsS3XZmb0BPbQhP4ZZ8DmDp4awpxj4HJ3u7uuZxPEBDozBCaKDasYYksVrRCcTN2zFgbRpjNDp+XfFwWnlBzlLeD5Z+SuKhul4cAfYatchxoAX2vdZLMxyFlkqb/3dTmDoUWURY9OJVy3bHDE6W4WEoun+2vrYofvfIiQBh/wK3tLrS92E6cmLzYytpdVZpm+UaCoKtv0ftFX8853YKzAuBkZNZ510GAFjn1DKHvphUjN1OuDCGoCMKn2O2+xXQ3RS3m1g9iNdnfZ9S6BwoGlmnev0q8oiV7KbDjdtJmgtvkwxq3XpGTnxQVuDevH4hTywRqDTvQ28gZzF7gJII8fNp1IvBIMVcOtuDxxcbin4O+B4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
